apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jrq7mptob-python 
  janus-idp.io/tekton: jrq7mptob-python
  backstage.io/kubernetes-id: jrq7mptob-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jrq7mptob-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  