apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jrq7mptob-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jrq7mptob-python 
  name: jrq7mptob-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jrq7mptob-python 
